# Fly configuration file for the start app for deploying it in fly.io site

app = "start"
primary_region = "ams"


#[deploy]
#  release_command = "npm run build"

[processes]
  app = "node index.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.1"

[[services]]
  http_checks = []
  internal_port = 3001
  processes = ["app"]

[http_service]
  force_https = true
  auto_stop_machines = true
  auto_start_machine = true
  min_machines_running = 0
  processes = ["app"]